linear_models:
  elastic_net:
    alpha:
    - 0.001
    - 0.01
    - 0.1
    - 1.0
    l1_ratio:
    - 0.1
    - 0.5
    - 0.7
    - 0.9
    max_iter:
    - 1000
  lasso:
    alpha:
    - 0.001
    - 0.01
    - 0.1
    - 1.0
    max_iter:
    - 1000
  ridge:
    alpha:
    - 0.1
    - 1.0
    - 10.0
    - 100.0
    solver:
    - auto
tree_models:
  lightgbm:
    bagging_fraction:
    - 0.8
    - 1.0
    feature_fraction:
    - 0.8
    - 1.0
    learning_rate:
    - 0.01
    - 0.1
    - 0.2
    n_estimators:
    - 100
    - 200
    - 300
    num_leaves:
    - 31
    - 50
    - 100
  random_forest:
    max_depth:
    - 10
    - 20
    - 30
    - null
    min_samples_leaf:
    - 1
    - 2
    - 4
    min_samples_split:
    - 2
    - 5
    - 10
    n_estimators:
    - 100
    - 200
    - 300
  xgboost:
    colsample_bytree:
    - 0.8
    - 1.0
    learning_rate:
    - 0.01
    - 0.1
    - 0.2
    max_depth:
    - 3
    - 6
    - 10
    n_estimators:
    - 100
    - 200
    - 300
    subsample:
    - 0.8
    - 1.0
