ensemble:
  base_models:
  - ridge
  - lasso
  - random_forest
  - xgboost
  meta_learner: ridge
  method: stacking
experiment:
  n_jobs: -1
  name: house_price_prediction
  random_state: 42
feature_engineering:
  box_cox_transform: true
  feature_selection:
    method: rfe
    n_features: 50
  interaction_terms: true
  polynomial_degree: 2
hyperparameter_tuning:
  cv_folds: 5
  method: optuna
  n_trials: 100
  timeout: 3600
